# Site settings
title: 顽童的梦与酒
description: "昏睡的顽童，梦就像烈酒"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "http://kamiknows.github.io/"

# User settings
username: Kami
user_title: Kami - FrontEnd
email: huany63@gmail.com
# twitter_username: loremipsum
# github_username:  loremipsum
# gplus_username:  loremipsum
# linkedin_public_url: loremipsum # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: kamiknows-github-io
profile_picture: /assets/img/avatar.jpg

# Build settings
markdown: kramdown
highlighter: rouge
# permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: 主页
      url: /
      key_trigger: 1
    # - title: 发布
    #   url: /posts
    #   key_trigger: 2
    - title: 分类
      url: /series
      key_trigger: 2
    - title: 标签
      url: /tags
      key_trigger: 3
    - title: 关于我
      url: /about
      key_trigger: 4
  section_2:
    - title: github
      url: https://github.com/kamiknows
      new_tab: true
      key_trigger: g
    # - title: twitter
    #   url: /
    #   key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
#   - name: fluany
#     url: https://github.com/fluany/fluany
#   - name: vim-frontend
#     url: https://github.com/victorvoid/vim-frontend
#   - name: generator-capybara
#     url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
